version: '3'

services:
  bot_frases:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot_frases

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email guilherme.lopes.freitas@gmail.com --agree-tos --no-eff-email -d botfrases.com

