services:
  bot_frases:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot_frases
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

