name: Deploy

on:
  push:
    branches:
      - main

run-name: Deploy to EC2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          command_timeout: 60m
          script: |
            cd scripts
            ./action_deploy.sh